LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := Lineage
LOCAL_SRC_FILES := Lineage.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
